#!/usr/bin/env bash
# Nightly auto-sync: scans ~/ for active Claude-workflow repos, proposes
# backports into the seeds repo, opens a stacked PR for review.
#
# Runs non-interactively. Driven by Windows Task Scheduler at 2am EDT.
set -euo pipefail

SEEDS_DIR="$HOME/seeds"
SCAN_ROOT="$HOME"
MAX_DEPTH=3
FRESHNESS_DAYS=7
REPO_CAP=10
DATE="$(date +%Y-%m-%d)"
LOG_DIR="$SEEDS_DIR/logs"
LOG_FILE="$LOG_DIR/nightly-sync-$DATE.log"
BRANCH="auto-sync/$DATE"

mkdir -p "$LOG_DIR"
exec > >(tee -a "$LOG_FILE") 2>&1

echo "=== Nightly sync started $(date -Iseconds) ==="

# 1. Find candidate .claude/ dirs modified in the freshness window.
mapfile -t CANDIDATES < <(
  find "$SCAN_ROOT" -maxdepth "$MAX_DEPTH" -type d -name .claude \
    -not -path "*/node_modules/*" \
    -mtime "-$FRESHNESS_DAYS" \
    2>/dev/null | sort -u
)

ACTIVE_REPOS=()
SKIPPED=()

for claude_dir in "${CANDIDATES[@]}"; do
  repo="$(dirname "$claude_dir")"

  # Never sync seeds into itself.
  [[ "$(realpath "$repo")" == "$(realpath "$SEEDS_DIR")" ]] && continue

  # Must be a git repo.
  if ! git -C "$repo" rev-parse --git-dir >/dev/null 2>&1; then
    echo "skip (not a git repo): $repo"
    continue
  fi

  # Skip dirty repos silently (log only).
  if [[ -n "$(git -C "$repo" status --porcelain 2>/dev/null)" ]]; then
    echo "skip (dirty): $repo"
    SKIPPED+=("$repo — uncommitted changes")
    continue
  fi

  # Pull latest. Fast-forward only; skip on conflict.
  if ! git -C "$repo" pull --ff-only --quiet 2>&1; then
    echo "skip (pull failed): $repo"
    SKIPPED+=("$repo — git pull --ff-only failed")
    continue
  fi

  ACTIVE_REPOS+=("$repo")

  # Respect the cap.
  if [[ ${#ACTIVE_REPOS[@]} -ge $REPO_CAP ]]; then
    echo "hit repo cap ($REPO_CAP); stopping scan"
    break
  fi
done

echo "Active repos (${#ACTIVE_REPOS[@]}): ${ACTIVE_REPOS[*]:-none}"
echo "Skipped (${#SKIPPED[@]}):"
printf '  - %s\n' "${SKIPPED[@]:-}"

if [[ ${#ACTIVE_REPOS[@]} -eq 0 ]]; then
  echo "Nothing to sync. Exiting clean."
  exit 0
fi

# 2. Prep the seeds branch.
cd "$SEEDS_DIR"
git fetch origin --quiet
git checkout -B "$BRANCH" origin/main

# 3. Invoke Claude non-interactively to do the per-repo sync work.
REPO_LIST="$(printf -- '- %s\n' "${ACTIVE_REPOS[@]}")"

PROMPT="$(cat <<EOF
You are acting as the @sync-config agent in non-interactive automation mode.

Working directory is the seeds repo ($SEEDS_DIR). You are on branch $BRANCH.

For each active repo below, diff its live Claude workflow files (.claude/agents,
.claude/skills, CLAUDE.md, docs/) against the corresponding templates in this
seeds repo. Classify every hunk per the sync-config agent's rules:

- SKIP project-specific substitutions (project names, deadlines, client-specific paths, stack picks)
- BACKPORT structural improvements (new steps, bug fixes, format changes, agent-prompt improvements)
- FLAG patterns appearing in both dev/ and domain/ contexts (describe, don't extract)

AUTOMATION RULES (override the agent's normal interactive behavior):
- Do NOT prompt the user. Make your own judgment calls.
- When you backport a hunk, replace project-specific strings with generic tokens
  ([Project], "the project deadline", etc.) as you apply it.
- Stage one commit per source repo, message: "sync-config: backport from <repo-name>"
  with a body listing the files changed and a one-line summary per hunk.
- If a repo has no backport-worthy changes, skip it silently (no empty commit).
- Flagged patterns go in the PR body only — do not modify shared/ or create new directories.
- Do NOT push, do NOT open a PR. The surrounding script does that.

Active repos:
$REPO_LIST

When done, write a short summary to stdout listing which repos produced commits
and any patterns flagged for future shared/ extraction.
EOF
)"

echo "--- Invoking Claude ---"
claude -p "$PROMPT" --permission-mode acceptEdits || {
  echo "Claude invocation failed. Leaving branch $BRANCH in place for inspection."
  exit 1
}

# 4. If no commits landed, clean up and exit.
COMMITS="$(git log origin/main.."$BRANCH" --oneline)"
if [[ -z "$COMMITS" ]]; then
  echo "No backport-worthy changes found. Deleting branch."
  git checkout main
  git branch -D "$BRANCH"
  exit 0
fi

# 5. Push and open PR.
git push -u origin "$BRANCH" --quiet

SKIPPED_BLOCK=""
if [[ ${#SKIPPED[@]} -gt 0 ]]; then
  SKIPPED_BLOCK="$(printf -- '- %s\n' "${SKIPPED[@]}")"
else
  SKIPPED_BLOCK="none"
fi

PR_BODY="$(cat <<EOF
Automated nightly sync — $DATE.

## Contributing repos
$REPO_LIST

## Skipped
$SKIPPED_BLOCK

## Commits on this branch
$COMMITS

Log: \`logs/nightly-sync-$DATE.log\`

Generated by \`scripts/nightly-sync.sh\`.
EOF
)"

gh pr create --title "auto-sync $DATE" --body "$PR_BODY" --base main --head "$BRANCH"

echo "=== Nightly sync finished $(date -Iseconds) ==="
